### ISSUE TITLE
Python 3 compatibility (NameError: name 'textfsm' is not defined during installation)

### ISSUE THREAD

**Issue by xavierhardy** [google/textfsm#12]
I can install `gtextfsm` using Python 2.7 but not using Python 3.5.

Python 2:
```sh
user@debian:/tmp$ virtualenv py27
New python executable in /tmp/py27/bin/python
Installing setuptools, pip, wheel...done.
user@debian:/tmp$ . ./py27/bin/activate
(py27) user@debian:/tmp$ python
Python 2.7.3 (default, Jun 21 2016, 18:38:19) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
(py27) user@debian:/tmp$ pip install gtextfsm
Collecting gtextfsm
Installing collected packages: gtextfsm
Successfully installed gtextfsm-0.2.1
```

Python 3:
```sh
user@debian:/tmp$ virtualenv-3.5 -p python3.5 py35
Already using interpreter /home/user/bin/python3.5
Using base prefix '/home/user'
New python executable in /tmp/py35/bin/python3.5
Also creating executable in /tmp/py35/bin/python
Installing setuptools, pip, wheel...done.
user@debian:/tmp$ . py35/bin/activate
(py35) user@debian:/tmp$ pip install gtextfsm
Collecting gtextfsm
  Using cached gtextfsm-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wpyy1qn6/gtextfsm/setup.py", line 19, in <module>
        import textfsm
      File "/tmp/pip-build-wpyy1qn6/gtextfsm/textfsm/__init__.py", line 2, in <module>
        __version__ = textfsm.__version__
    NameError: name 'textfsm' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wpyy1qn6/gtextfsm/
```

**Comment by xavierhardy** [comment]
The pull request named `Python-3 deepcopy fix and close all files (except stdin): version 0.3.2` (#14) fixes the remaining errors in both the tests and the CLI.

**Comment by termlen0** [comment]
I still see this error.. maybe not pushed into pyPI ?

**Comment by q1x** [comment]
Same here

**Comment by harro** [comment]
Note, the PyPi package is maintained here - https://pypi.org/project/textfsm/
Let us know if you are having issues with this one.

**Comment by rohitchormale** [comment]
I am still getting the issue. 
Below is environment 
textfsm==0.4.1
ntc_templates==1.0.0
python 3.7.2
Tested in virtualenv

**Comment by damasoavalos** [comment]
Any idea how to fix this issue?

**Comment by harro** [comment]
I cannot reproduce the behavior with virtualenv Python 3.5 or 3.7 and textfsm-1.1.0
