### ISSUE TITLE
pip install textfsm fails for python3.4

### ISSUE THREAD

**Issue by rokkhan** [google/textfsm#57]
I am unable to install textfsm with puython3.4

Collecting textfsm (from netmiko)
  Downloading https://files.pythonhosted.org/packages/a1/0d/a1b490503545b3b4600b965eae5d44cc2b6ce27cfb44f4debc563dbb56d3/textfsm-0.4.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/textfsm.egg-info
    writing pip-egg-info/textfsm.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a2cvg8zh/textfsm/setup.py", line 50, in <module>
        'texttable', 'terminal'])
      File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 289, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 621, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib64/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 165, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib64/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-a2cvg8zh/textfsm/

**Comment by harro** [comment]
Please re-try with latest version (1.1.0) - https://pypi.org/project/textfsm/

**Comment by harro** [comment]
Re-open if this is still a problem. Closing for now on the assumption that latest release addresses this issue.
